version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
volumes:
  node_modules:
