name: frontend style check

on:
  workflow_call:

jobs:
  lint:
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        node: [18]
        os: [ubuntu-latest]

    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v2

      - name: Setup node env 🔧
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies 🧹
        run: npm ci

      - name: Run linter 👀
        run: npm run lint
